---
- name: Installing Veeam ONE Install (Typical Deployment)
  gather_facts: false
  hosts: all
  vars:
    version: "12"
    iso_download: false #this way ISO is only downloaded once
    sql_express_setup: true
    sql_service_username: "{{ sql_service_username }}"
    sql_service_password: "{{ sql_service_password }}"
    one_create_service_account: true #true==local false==domain
    one_username: "{{ one_username }}"
    one_password: "{{ one_password }}"
    # https://docs.ansible.com/ansible/latest/vault_guide/vault_encrypting_content.html#creating-encrypted-variables
  tasks:
    - name: Veeam ONE Server installation tasks
      include_role:
        name: veeamhub.veeam.veeam_vas
        tasks_from: one_server_install
      vars:
        iso_download: true #this way ISO is only downloaded once
    - name: Veeam ONE Web UI installation tasks
      include_role:
        name: veeamhub.veeam.veeam_vas
        tasks_from: one_web_ui_install
    - name: Veeam ONE Monitoring Client installation tasks
      include_role:
        name: veeamhub.veeam.veeam_vas
        tasks_from: one_client_install